spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      uri: mongodb://test1:test1234@192.168.45.135:17017/webflux-movie?authSource=admin&authMechanism=SCRAM-SHA-1
      database: webflux-movie