spring:
  config:
    activate:
      on-profile: prod

  data:
    mongodb:
      uri: mongodb://test1:test1234@192.168.35.135:17017/webflux-movie?authSource=admin&authMechanism=SCRAM-SHA-1
      database: webflux-movie